version: "3"

services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    ports:
      - "3010:3000"
    volumes:
      - ./data:/etc/semaphore
    env_file: stack.env
    restart: unless-stopped
