services:
  # uncomment this section and comment out the mysql section to use postgres instead of mysql
  postgres:
    restart: unless-stopped
    image: postgres:14
    hostname: postgres
    volumes: 
      - semaphore-postgres:/var/lib/postgresql/data
    env_file: stack.env
  semaphore:
    restart: unless-stopped
    ports:
      - 3010:3000
    image: semaphoreui/semaphore:latest
    env_file: stack.env
    depends_on:
      - postgres # for postgres, change to: postgres
volumes:
  semaphore-postgres: # to use postgres, switch to: semaphore-postgres
